version: "3.9"

services:
  python-executor:
    build: .
    container_name: python-executor-container
    ports:
      - "8000:8000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      uvicorn executor:app --host 0.0.0.0 --port 8000
